### ISSUE TITLE
Regression: HDR tonemapping stopped working in 1.12.0

### ISSUE THREAD

**Issue by mihawk90** [jellyfin/jellyfin-desktop#897]
**Describe the bug**
After updating to 1.12.0 HDR tone-mapping stops working. The media is direct play (as expected), so tone-mapping *should* happen client side. This works perfectly fine when downgrading to 1.11.1, so it is not a host issue.

From what I can tell the logs don't indicate whether or not tonemapping is attempted:
* [1.12.0 jellyfinmediaplayer.log](https://github.com/user-attachments/files/19595013/jellyfinmediaplayer.log)
* [1.11.1 jellyfinmediaplayer.log](https://github.com/user-attachments/files/19595032/jellyfinmediaplayer.log)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install or upgrade to JMP 1.12.0.
2. Play any HDR10 media.
3. Clearly no tone-mapping is going on as can be seen by typical washed-out colour.
4. Downgrade to 1.11.1.
5. Play the same media.
6. Colors are accurately tone-mapped.

**Expected behaviour**
Tone-mapping should continue to function as in previous versions.

**Screenshots**
1.12.0:
![Image](https://github.com/user-attachments/assets/e6bcecfb-4fc4-46e5-9401-93c7bb1e068e)

1.11.1:
![Image](https://github.com/user-attachments/assets/d58d65ac-0e8b-4d00-bdfd-408ca2e552ab)

**Desktop (please complete the following information):**
 - OS: Linux (Fedora)
 - Version: 1.12.0
 - Installation Method: Flatpak

**Additional context**
This *might* possibly be related to #883 (one comment in #165 [#issuecomment-2495938416 ](https://github.com/jellyfin/jellyfin-media-player/issues/165#issuecomment-2495938416) already mentions "muted colors"). It might be that due to Qt running on software rendering, it isn't seeing whether or not the display supports HDR. Although in that case I would expect it to always fall back to tone-mapping.

**Comment by TheNexter** [comment]
Same issue

**Comment by EmilZackrisson** [comment]
Same issue here on macOS

**Comment by javierzhang0504** [comment]
same issue on macOS

**Comment by mihawk90** [comment]
OK soooooo I was about to look into this and do a bisect for what caused it. Turns out the issue doesn't appear to be JMP itself.

I did a build 1.11.1 according to the build instructions, and I'm still seeing the same issue. Since the build instructions only clone mpv master, which in turn clones ffmpeg master, I assume the issue is with libmpv in some shape or form, maybe a default that changed or something, IDK.

Bisecting mpv is not gonna be fun tho :/

PS: Please don't post this kind of "Me too" comments, that's what reactions are for. They clog the thread for no benefit and send a notification/e-mail everytime to every maintainer, that's not really helpful.

**Comment by EmilZackrisson** [comment]
I just forked and built from master via the macOS arm64 workflow, and the issue seems gone. Both HDR10 and Dolby Vision play with tone mapping and direct play without looking dull. Don't know what changed since last I tried.

**Comment by TheNexter** [comment]
@EmilZackrisson Weird, any one on linux can try to rebuild it to see if bug is gone now ? :(

**Comment by mihawk90** [comment]
I built on master first and had the issue.

**Comment by EmilZackrisson** [comment]
> I built on master first and had the issue.

Did you try again now? I also built from main before but it worked now. I think it was one of the dependencies and that it's fixed now.

**Comment by mihawk90** [comment]
There haven't been any commits for 3 weeks, much less anything that would address this.

But regardless I just did another build off master with all the dependencies on master as well and I'm still seeing the same.

I can't bisect this without having a working version though and I don't know why I'm seeing the same on 1.11.1, and I didn't get a response on Matrix either.

**Comment by Cwavs** [comment]
> edit: OK now I'm confused :/ I built 1.11.1 and forced the old versions of `mpv`, `ffmpeg`, `libplacebo`, and `libass` from the Flatpak manifest: https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/blob/63685e0f239c457e589878b4e06e855c7faf9f75/com.github.iwalton3.jellyfin-media-player.json
> 
> But I'm still seeing the same issue… IDK how that is possible :/

Is it possible the issue is related to the flatpak runtime somehow? I know I saw something similar on another issue where it seems to have been introduced by the runtime it's based on being updated.

**Comment by mihawk90** [comment]
> Is it possible the issue is related to the flatpak runtime somehow?

Building the old version also builds with the old runtime.

https://github.com/flathub/com.github.iwalton3.jellyfin-media-player/blob/63685e0f239c457e589878b4e06e855c7faf9f75/com.github.iwalton3.jellyfin-media-player.json#L3-L4

**Comment by Cwavs** [comment]
Ah that makes sense, weird. Something outside the container must be affecting it then...

**Comment by mihawk90** [comment]
That was my thought too, but why does it not affect 1.11 on Flathub then? And why is 1.12 universally broken for everyone here then? It doesn't make sense either which way you look at it.

**Comment by tiaringhio** [comment]
same issue here, downgraded to 1.11.1 and it looks way better, still not as good as playing with IINA on MacOS for reasons i don't know

**Comment by baronefr** [comment]
Same issue on macOs. Downgrade solves.

**Comment by TheNexter** [comment]
@mihawk90 Any news about this bug ? Want to switch off plex but i cannot due to this only issue :(

**Comment by mihawk90** [comment]
I stopped looking into it since on 2 separate days asking on Matrix I got no response, and obviously this issue is also dead so.. 🤷 

I'm happy to do a bisect but I can't do that when I don't have a good working build and getting no response of what could be the reason for that.

**Comment by ghost** [comment]
Adding a bit of extra information, the bug seems to be Flatpak specific. I compared the Flatpak build with the one in the Arch User repositories (version 1.12.0), and the HDR problems do not seem to exist.
With that said, I tried playing the movie file itself in raw MPV, and I get the same result whether I install MPV through Flatpak or the Arch repositories, so I doubt it is specifically a bug with Flatpak on the large.

**Comment by TheNexter** [comment]
That so sad, after all this time, the only true alternative to plex let this very basic issue ignore :(

**Comment by GiuseppeIgnone** [comment]
I have the same problem using JMP 1.12.0 Flatpak on Linux Mint 22.2. the colors are grey compared to the web version

**Comment by BlackStar153** [comment]
Downgrading to 1.11.1 also helped me.
Will the error be fixed at some point, or is it being worked on?
The Android app doesn't work at all. It immediately displays a media player error.

**Comment by mihawk90** [comment]
Given that I filed this within days after the release and no maintainer seems to have even acknowledged it, I'm not keeping my hopes up anymore.
I just pray that 1.11 is still going to work for a while 🤷 

Maybe I'll get the urge again at some point.

---

Also, I need to correct something I said in an [earlier comment](#issuecomment-3167546719):

> > Is it possible the issue is related to the flatpak runtime somehow?
> 
> Building the old version also builds with the old runtime.

At that point it had already been a while since I looked into it, but it occurred to me later that I wasn't actually building the Flatpak.
I was doing a native build using all the same versions that 1.11.1 was using, and still hitting the issue. So either it's an implicit dependency or the Flatpak runtime.

I don't remember why I didn't build the Flatpak, but Bisecting would probably be a PITA anyway because building the Flatpak involves also building every dependency every time, after adjusting the Flatpak manifest. I'd need to figure out how to install these in the first place and I'm just not in the mood for that at the moment.

**Comment by BlackStar153** [comment]
Hello, 
I have now found out when the problem was fixed. I have downloaded and installed the AUR version, and the HDR content is working again. Version 1.12.05 is available and has apparently been fixed.
Here is the link for Arch users: https://aur.archlinux.org/packages/jellyfin-media-player 

Have Fun :)

**Comment by mihawk90** [comment]
Nothing in that contains any fixes whatsoever.

1. You're reading the version wrong and the version you mention doesn't exist.
2. The 2 patches are entirely unrelated.
3. It was [mentioned before](#issuecomment-3314586629) that the AUR build is not affected. We don't know why, but it is not "fixed" there. And yes there is a difference between *unaffected* and *fixed*.

**Comment by flobere** [comment]
just noting for non Arch/AUR users: Although this isn't fixed, the Jellyfin Desktop flatpak is now on flathub, and doesn't seem to have this issue.

**Comment by mihawk90** [comment]
> the Jellyfin Desktop flatpak is now on flathub, and doesn't seem to have this issue.

Not sure what you mean with "now" because it has been for years (unless you're referring to a different client?), but *cough*:

> * Version: 1.12.0
> * Installation Method: ***Flatpak***

Yes, non-Arch users do indeed exist. Shocking, I know.


Though I haven't tested 1.12.0 in a while due to this and #883 making the client "unpleasant" to use.

edit:
I see now what you mean. 2.0 changes the appID and name 🫠 

---

I tested 2.0 and it seems tonemapping is indeed back, though it appears slightly darker (might be just imagining and/or inaccurate colours of the screenshot though). Interestingly passing `--disable-gpu` (the option that was reverted in 2a3dada) doesn't slow down the client nor does it impede tonemapping. So either it was unrelated to both, or it's not actually working, which would make me question (again) what flag was talked about when closing #883.

**Comment by Unvarying8964** [comment]
> > the Jellyfin Desktop flatpak is now on flathub, and doesn't seem to have this issue.
> 
> Not sure what you mean with "now" because it has been for years (unless you're referring to a different client?), but _cough_:
> 
> > * Version: 1.12.0
> > * Installation Method: _**Flatpak**_
> 
> Yes, non-Arch users do indeed exist. Shocking, I know.
> 
> Though I haven't tested 1.12.0 in a while due to this and [#883](https://github.com/jellyfin/jellyfin-desktop/issues/883) making the client "unpleasant" to use.
> 
> edit: I see now what you mean. 2.0 changes the appID and name 🫠
> 
> I tested 2.0 and it seems tonemapping is indeed back, though it appears slightly darker (might be just imagining and/or inaccurate colours of the screenshot though). Interestingly passing `--disable-gpu` (the option that was reverted in [2a3dada](https://github.com/jellyfin/jellyfin-desktop/commit/2a3dadae071aad69357f8234dc87e9b6f15e18b2)) doesn't slow down the client nor does it impede tonemapping. So either it was unrelated to both, or it's not actually working, which would make me question (again) what flag was talked about when closing [#883](https://github.com/jellyfin/jellyfin-desktop/issues/883).

Hello,
I've been trying to compare some medias against mpv to see If I can at least get a vague Idea about the accuracy of the JMP tonemap. Results are vague and inconsistend, especially when I force a ICC profile. I have no idea how JMP is actually applying tonemap.

**Comment by Cwavs** [comment]
> > > the Jellyfin Desktop flatpak is now on flathub, and doesn't seem to have this issue.
> > 
> > 
> > Not sure what you mean with "now" because it has been for years (unless you're referring to a different client?), but _cough_:
> > > * Version: 1.12.0
> > > * Installation Method: _**Flatpak**_
> > 
> > 
> > Yes, non-Arch users do indeed exist. Shocking, I know.
> > Though I haven't tested 1.12.0 in a while due to this and [#883](https://github.com/jellyfin/jellyfin-desktop/issues/883) making the client "unpleasant" to use.
> > edit: I see now what you mean. 2.0 changes the appID and name 🫠
> > I tested 2.0 and it seems tonemapping is indeed back, though it appears slightly darker (might be just imagining and/or inaccurate colours of the screenshot though). Interestingly passing `--disable-gpu` (the option that was reverted in [2a3dada](https://github.com/jellyfin/jellyfin-desktop/commit/2a3dadae071aad69357f8234dc87e9b6f15e18b2)) doesn't slow down the client nor does it impede tonemapping. So either it was unrelated to both, or it's not actually working, which would make me question (again) what flag was talked about when closing [#883](https://github.com/jellyfin/jellyfin-desktop/issues/883).
> 
> Hello, I've been trying to compare some medias against mpv to see If I can at least get a vague Idea about the accuracy of the JMP tonemap. Results are vague and inconsistend, especially when I force a ICC profile. I have no idea how JMP is actually applying tonemap.

JMP (at least historically) used MPV for playback, so I presume any tone mapping was handled mostly by MPV, so you probably want to check their docs. MPV also uses ffmpeg under the hood so you might also want to checkout the ffmpeg docs. If you're looking for help from the devs, you'll probably want to open a new thread as this one seems like it's not gonna get a response from the devs anytime soon, especially with Jellyfin Desktop (the 2.0 of Jellyfin Media Player) doesn't seem to have this issue.

**Comment by Cwavs** [comment]
Given that, I'd guess this can probably be closed seeing as it seems to be working in 2.0 then...

**Comment by mihawk90** [comment]
> * Anything older than v2.0 is no longer supported.

I'll say this is a bit of an odd position to take when the 2.0 release is tagged as a pre-release and from comments I saw elsewhere (not sure where, might have been Matrix) "not quite ready yet" (though in that case why is it not a beta?).
I understand not wanting to support older versions, but then there should be a full replacement version that is intended for the general public.

I use 2.0, but I also wouldn't consider myself a typical user after making a package for it. The majority of users avoids Pre-Releases, and for good reason.

The main Jellyfin website even still links to the 1.12 client on Flathub (as well as the old repo name). You can put it on the main website, or you can call it unsupported, but you can't have both.

**Comment by Cwavs** [comment]
I'd guess it's not supported in the sense they don't plan to fix any bugs with 1.12 as they'd rather focus on getting 2.0 ready, but until then 1.12 still works fine in most use cases. So although it currently isn't supported, is still the recommended version for most people.

**Comment by mihawk90** [comment]
I understand all that and I am not saying there should be another release. I am saying it's mixed messaging at best.
At the very least I would leave this issue open for others to find when they are experiencing the same issue. Because as long as there isn't a new release (and with that obviously I mean a *full* release, not pre-release), this is not "fixed", and the average user doesn't search closed issues (hell half of them don't search open issues either, but that's besides the point).
